# Generated by Django 3.1 on 2020-09-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStatus', '0003_auto_20200829_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('major', models.CharField(choices=[('Veterinary Technology', 'Veterinary Technology'), ('Equine Studies', 'Equine Studies'), ('Interactive Media Design', 'Interactive Media Design'), ('Emerging Media & Content Creation', 'Emerging Media & Content Creation'), ('Applied Computer Science', 'Applied Computer Science'), ('Criminal Justice', 'Criminal Justice'), ('Nursing', 'Nursing'), ('Psychology, Mental Health Counseling', 'Psychology, Mental Health Counseling')], max_length=200, null=True)),
                ('school', models.CharField(choices=[('Boston Latin School', 'Boston Latin School'), ('Sturgis Charter Public School', 'Sturgis Charter Public School'), ('Hopkinton High School', 'Hopkinton High School'), ('Advanced Math and Science Academy', 'Advanced Math and Science Academy'), ('Dover-Sherborn Regional High School', 'Dover-Sherborn Regional High School'), ('Mystic Valley Regional Charter School', 'Mystic Valley Regional Charter School'), ('Lexington High School', 'Lexington High School'), ('Weston High School', 'Weston High School')], max_length=200, null=True)),
                ('GPA', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='gpa',
            new_name='GPA',
        ),
    ]
