# Generated by Django 3.1 on 2020-09-12 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStatus', '0006_auto_20200911_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='GPA',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
