# Generated by Django 3.1 on 2020-09-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStatus', '0008_auto_20200912_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], max_length=200, null=True),
        ),
    ]
