# Generated by Django 3.1 on 2020-09-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStatus', '0012_auto_20200914_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_submitted',
            field=models.CharField(blank=True, choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted')], default='Not Submitted', max_length=25, null=True),
        ),
    ]
